import os
import smtplib
from email.message import EmailMessage
import logging
from dotenv import load_dotenv

logger = logging.getLogger(__name__)

def send_medical_report_email(to_email: str, patient_name: str, pdf_bytes: bytes) -> tuple[bool, str]:
    """Sends the generated PDF medical report via email."""
    load_dotenv(override=True)
    smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", 465))
    smtp_user = os.getenv("SMTP_USER")
    smtp_pass = os.getenv("SMTP_PASSWORD")

    if not smtp_user or not smtp_pass or "your_email" in smtp_user:
        return False, "Email credentials are not configured in .env"

    try:
        msg = EmailMessage()
        msg['Subject'] = f"Medical Diagnostic Report - {patient_name}"
        msg['From'] = smtp_user
        msg['To'] = to_email
        
        msg.set_content(
            f"Hello,\n\nPlease find the attached Medical Diagnostic Report for {patient_name}.\n\n"
            f"This is an automated report generated by the Medical Multimodal System.\n\n"
            f"Regards,\nMedical Multimodal Diagnostics Team"
        )

        msg.add_attachment(
            pdf_bytes,
            maintype='application',
            subtype='pdf',
            filename=f"Medical_Report_{patient_name.replace(' ', '_')}.pdf"
        )

        import socket
        # Force IPv4 to prevent Network is unreachable (Errno 101) on IPv6
        orig_getaddrinfo = socket.getaddrinfo
        def _ipv4_getaddrinfo(host, port, family=0, type=0, proto=0, flags=0):
            return orig_getaddrinfo(host, port, socket.AF_INET, type, proto, flags)
        socket.getaddrinfo = _ipv4_getaddrinfo

        with smtplib.SMTP_SSL(smtp_server, smtp_port) as server:
            server.login(smtp_user, smtp_pass)
            server.send_message(msg)
            
        # Restore original getaddrinfo
        socket.getaddrinfo = orig_getaddrinfo
            
        logger.info(f"Report emailed successfully to {to_email}")
        return True, "Success"
    except Exception as e:
        err_msg = str(e)
        logger.error(f"Failed to send email to {to_email}: {err_msg}")
        return False, err_msg
